### ISSUE TITLE
Fix out of date docs

### ISSUE THREAD

**Issue by sinistersnare** [Ogeon/rustful#120]
As discussed on Gitter, [rustful::server::Listening](https://ogeon.github.io/docs/rustful/master/rustful/server/struct.Listening.html) has some out of date docs. It states that `fn close` does not work, but the linked issue is now closed. Fixing this should be fun and ez. 

Looking more closely, this is actually a struct in Hyper re-exported here, ill add this issue to Hyper, and not here....

**Comment by sinistersnare** [comment]
This is fixed in master in Hyper, but is not released. When they cut a new release, and we update, it will be fixed.

**Comment by Ogeon** [comment]
Oh, you know what? I just realized that `Listening` this is reexported from Hyper, so no wonder that I had no recollection of that note. I'm definitely getting too tired. Too many meetings... I'll close this straight away, since it's on their side and the upcoming async API will also probably not reexport it at all.

Still, thank you for taking your time to report this., and sorry for not realizing it earlier.
